services:
  - type: web
    plan: free
    name: tecnico-medio-django
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn tecnico_medio.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tecnico-medio-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: tecnico-medio-db
    plan: free
    databaseName: tecnico_medio
    user: tecnico_medio 