services:
  - type: web
    name: tecnico-medio-django
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn tecnico_medio.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.0"

databases:
  - name: tecnico-medio-db
    databaseName: tecnico_medio_db
    user: tecnico_medio_user 